markdown: rdiscount
exclude: [sass]
pygments: true
permalink: /:year/:month/:title

# Gegenral Info
title: Blog de Ricardo Ramirez
author: Ricardo Ramirez
description: Ricardo Ramirez es un Front-End Developer que vive en El Salvador con interes en arquitectura, rendimiento y escabilidad en CSS.
url: http://ricardoerl.com

# Open Graph

og_image: images/logo-photo.jpg 
og_image_type: image/png
fb_profile_id: 772745716