markdown: rdiscount
exclude: [sass]
pygments: true
permalink: /:year/:month/:title

# Info
title: Blog de Ricardo Ram&iacute;rez
author: Ricardo Ram&iacute;rez
email: hola@ricardoerl.com
description: Ricardo Ram&iacute;rez es un Front-End Developer y diseñador web de El Salvador
url: http://ricardoerl.com

# Open Graph

og_image: images/logo-photo.png 
og_image_type: image/png
og_image_width: 300
og_image_height: 300
fb_profile_id: 772745716